version: 2
var_1: &cache_key v1-dependencies-{{ checksum "package-lock.json" }}
var_2: &run_node
  docker:
    - image: circleci/node:12.13.0
var_3: &run_cypress
  docker:
    - image: cypress/base:12.13.0

jobs:
  install:
    <<: *run_node
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm install
      - save_cache:
          key: *cache_key
          paths:
            - node_modules
  lint:
    <<: *run_node
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm run lint ||
          (echo "Lint errors detected. Please run ''npm lint --fix''" ; exit 1)

  test:
    <<: *run_node
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: dist
      - run: npm run test.ci -- --reporters=default --reporters=jest-junit --maxWorkers=2
      - store_test_results:
          path: ./junit.xml
  test-e2e:
    <<: *run_cypress
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: dist
      - run: npm run e2e

  build-libs:
    <<: *run_node
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          command: npm run build.all.libraries
      - persist_to_workspace:
          root: dist
          paths:
            - ./*
  build-app:
    <<: *run_node
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: dist
      - run:
          command: npm run app.build.prod

workflows:
  version: 2
  install-lint-test-build:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - install
      - build-libs:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build-libs
          filters:
            tags:
              only: /.*/
      - test-e2e:
          requires:
            - build-libs
          filters:
            tags:
              only: /.*/
      - build-app:
          requires:
            - install
            - test
            - test-e2e
            - build-libs
          filters:
            tags:
              only: /.*/
