name: pr

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  setup:
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: [14,16]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-xlayers-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-
      - name: Install Dependencies
        run: npm install --force --legacy-peers
  lint:
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}

    needs: [setup]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: [14, 16]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-xlayers-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-
      - name: Run lint
        run: npm run affected:lint -- --base=origin/main --head=HEAD --parallel
  test:
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}

    needs: [setup]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: [14, 16]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-xlayers-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-
      - name: Run test
        run: npm run affected:test -- --base=origin/main --head=HEAD --parallel
  e2e:
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}

    needs: [setup]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: [14, 16]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: Run e2e
        run: npm run affected:e2e -- --base=origin/main --head=HEAD --parallel
  build:
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    runs-on: ${{ matrix.os }}

    needs: [setup, lint, test]
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: [14, 16]
    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Get origin main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main
      - uses: actions/cache@v1
        id: workspace-xlayers-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-xlayers-workspace-
      - name: Run build
        run: npm run affected:build -- --base=origin/main --head=HEAD --parallel
